In [1]:
# imports
import numpy as np

In [2]:
# numpy use examples

# numpy array
array = np.array([1, 2, 3, 4, 5]) 
print (f'array = {array}')

# numpy version
print (f'\nnumpy version = {np.__version__}')

# numpy object type
print (f'\nnumpy array type = {type(array)}')

# creating numpy array from tuple
tuple_object = (1, 2, 3, 4, 5)
array = np.array(tuple_object)
print (f'\ntuple_object type = {type(tuple_object)}')
print (f'numpy array type = {type(array)}')

# creating 0-D array
array_0d = np.array(42)
print(f'\n0-D array = {array_0d}')
print(f'0-D array shape = {array_0d.shape}')
print(f'0-D array dimentions = {array_0d.ndim}')

# creating 1-D array
array_1d = np.array([1, 2, 3, 4, 5])
print(f'\n1-D array = {array_1d}')
print(f'1-D array shape = {array_1d.shape}')
print(f'1-D array dimentions = {array_1d.ndim}')


# creating 2-D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f'\n2-D array =\n{array_2d}')
print(f'2-D array shape = {array_2d.shape}')
print(f'2-D array dimentions = {array_2d.ndim}')


# creating 3-D array
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(f'\n3-D array =\n{array_3d}')
print(f'3-D array shape = {array_3d.shape}')
print(f'3-D array dimentions = {array_3d.ndim}')

# creating a nth dimention numpy array
n = 10
array_nd = np.array([1, 2, 3, 4], ndmin=n)
print(f'\nn-D array =\n{array_nd}')
print(f'n-D array shape = {array_nd.shape}')
print(f'n-D array dimentions = {array_nd.ndim}')



array = [1 2 3 4 5]

numpy version = 1.24.2

numpy array type = <class 'numpy.ndarray'>

tuple_object type = <class 'tuple'>
numpy array type = <class 'numpy.ndarray'>

0-D array = 42
0-D array shape = ()
0-D array dimentions = 0

1-D array = [1 2 3 4 5]
1-D array shape = (5,)
1-D array dimentions = 1

2-D array =
[[1 2 3]
 [4 5 6]]
2-D array shape = (2, 3)
2-D array dimentions = 2

3-D array =
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3-D array shape = (2, 2, 3)
3-D array dimentions = 3

n-D array =
[[[[[[[[[[1 2 3 4]]]]]]]]]]
n-D array shape = (1, 1, 1, 1, 1, 1, 1, 1, 1, 4)
n-D array dimentions = 10


In [17]:
# numpy array indexing/accessing
print(f'\n1-D array = {array_1d}')

print ('\n')
for i in range(0, array_1d.shape[0]):
    print (f'{i}th element of 1-D array = {array_1d[i]}')
    
print ('\n')
print (f'last element of 1-D array = {array_1d[-1]}')

print(f'\n2-D array =\n{array_2d}')

print ('\n')
for i in range(0, array_2d.shape[0]):
    for j in range (0, array_2d.shape[1]):
        print (f'{i}th row, {j}th column of 2-D array = {array_2d[i][j]}')

print ('\n')
print (f'last row of 2-D array = {array_2d[-1]}')
print (f'last element of 2-D array = {array_2d[-1][-1]}')


1-D array = [1 2 3 4 5]


0th element of 1-D array = 1
1th element of 1-D array = 2
2th element of 1-D array = 3
3th element of 1-D array = 4
4th element of 1-D array = 5


last element of 1-D array = 5

2-D array =
[[1 2 3]
 [4 5 6]]


0th row, 0th column of 2-D array = 1
0th row, 1th column of 2-D array = 2
0th row, 2th column of 2-D array = 3
1th row, 0th column of 2-D array = 4
1th row, 1th column of 2-D array = 5
1th row, 2th column of 2-D array = 6


last row of 2-D array = [4 5 6]
last element of 2-D array = 6


In [30]:
# 1-D array slicing (startIndex, endIndex - excluded)
print(array_1d[1:4])
print(array_1d[2:])
print(array_1d[:2])
print(array_1d[-3:-1])

# 1-D slicing with step (startIndex, endIndex - excluded, stepSize)
print('\n')
print(array_1d[0:4:2])

# 2-D array slicing 
# From the second element, slice elements from index 1 to index 4 (not included):
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print('\n')
print(arr)
print(arr[1, 1:4]) 

[2 3 4]
[3 4 5]
[1 2]
[3 4]


[1 3]


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]


In [34]:
# numpy data types

print('\n')
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

print('\n')
arr = np.array(['apple', 'banana', 'cherry'])
print(arr)
print(arr.dtype) 

# creating array with specific datatype
print('\n')
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype) 


# Converting Data Type on Existing Arrays
print('\n')
arr = np.array([1.1, 2.1, 3.1])
print(arr.dtype)
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)



[1 2 3 4]
int32


['apple' 'banana' 'cherry']
<U6


[b'1' b'2' b'3' b'4']
|S1


float64
[1 2 3]
int32
